package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPackageByNameParams creates a new GetPackageByNameParams object
// with the default values initialized.
func NewGetPackageByNameParams() *GetPackageByNameParams {
	var ()
	return &GetPackageByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPackageByNameParamsWithTimeout creates a new GetPackageByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPackageByNameParamsWithTimeout(timeout time.Duration) *GetPackageByNameParams {
	var ()
	return &GetPackageByNameParams{

		timeout: timeout,
	}
}

// NewGetPackageByNameParamsWithContext creates a new GetPackageByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPackageByNameParamsWithContext(ctx context.Context) *GetPackageByNameParams {
	var ()
	return &GetPackageByNameParams{

		Context: ctx,
	}
}

/*GetPackageByNameParams contains all the parameters to send to the API endpoint
for the get package by name operation typically these are written to a http.Request
*/
type GetPackageByNameParams struct {

	/*Namespace
	  The entity namespace

	*/
	Namespace string
	/*PackageName
	  Name of package to fetch

	*/
	PackageName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get package by name params
func (o *GetPackageByNameParams) WithTimeout(timeout time.Duration) *GetPackageByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get package by name params
func (o *GetPackageByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get package by name params
func (o *GetPackageByNameParams) WithContext(ctx context.Context) *GetPackageByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get package by name params
func (o *GetPackageByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithNamespace adds the namespace to the get package by name params
func (o *GetPackageByNameParams) WithNamespace(namespace string) *GetPackageByNameParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get package by name params
func (o *GetPackageByNameParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithPackageName adds the packageName to the get package by name params
func (o *GetPackageByNameParams) WithPackageName(packageName string) *GetPackageByNameParams {
	o.SetPackageName(packageName)
	return o
}

// SetPackageName adds the packageName to the get package by name params
func (o *GetPackageByNameParams) SetPackageName(packageName string) {
	o.PackageName = packageName
}

// WriteToRequest writes these params to a swagger request
func (o *GetPackageByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param packageName
	if err := r.SetPathParam("packageName", o.PackageName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
