package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteTriggerParams creates a new DeleteTriggerParams object
// with the default values initialized.
func NewDeleteTriggerParams() *DeleteTriggerParams {
	var ()
	return &DeleteTriggerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTriggerParamsWithTimeout creates a new DeleteTriggerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteTriggerParamsWithTimeout(timeout time.Duration) *DeleteTriggerParams {
	var ()
	return &DeleteTriggerParams{

		timeout: timeout,
	}
}

// NewDeleteTriggerParamsWithContext creates a new DeleteTriggerParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteTriggerParamsWithContext(ctx context.Context) *DeleteTriggerParams {
	var ()
	return &DeleteTriggerParams{

		Context: ctx,
	}
}

/*DeleteTriggerParams contains all the parameters to send to the API endpoint
for the delete trigger operation typically these are written to a http.Request
*/
type DeleteTriggerParams struct {

	/*Namespace
	  The entity namespace

	*/
	Namespace string
	/*TriggerName
	  Name of trigger to delete

	*/
	TriggerName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete trigger params
func (o *DeleteTriggerParams) WithTimeout(timeout time.Duration) *DeleteTriggerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete trigger params
func (o *DeleteTriggerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete trigger params
func (o *DeleteTriggerParams) WithContext(ctx context.Context) *DeleteTriggerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete trigger params
func (o *DeleteTriggerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithNamespace adds the namespace to the delete trigger params
func (o *DeleteTriggerParams) WithNamespace(namespace string) *DeleteTriggerParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the delete trigger params
func (o *DeleteTriggerParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithTriggerName adds the triggerName to the delete trigger params
func (o *DeleteTriggerParams) WithTriggerName(triggerName string) *DeleteTriggerParams {
	o.SetTriggerName(triggerName)
	return o
}

// SetTriggerName adds the triggerName to the delete trigger params
func (o *DeleteTriggerParams) SetTriggerName(triggerName string) {
	o.TriggerName = triggerName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTriggerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param triggerName
	if err := r.SetPathParam("triggerName", o.TriggerName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
