package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/c3sr/openwhisk-go/swagger_models"
)

// NewFireTriggerParams creates a new FireTriggerParams object
// with the default values initialized.
func NewFireTriggerParams() *FireTriggerParams {
	var ()
	return &FireTriggerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFireTriggerParamsWithTimeout creates a new FireTriggerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFireTriggerParamsWithTimeout(timeout time.Duration) *FireTriggerParams {
	var ()
	return &FireTriggerParams{

		timeout: timeout,
	}
}

// NewFireTriggerParamsWithContext creates a new FireTriggerParams object
// with the default values initialized, and the ability to set a context for a request
func NewFireTriggerParamsWithContext(ctx context.Context) *FireTriggerParams {
	var ()
	return &FireTriggerParams{

		Context: ctx,
	}
}

/*FireTriggerParams contains all the parameters to send to the API endpoint
for the fire trigger operation typically these are written to a http.Request
*/
type FireTriggerParams struct {

	/*Namespace
	  The entity namespace

	*/
	Namespace string
	/*Payload
	  The trigger payload

	*/
	Payload *swagger_models.KeyValue
	/*TriggerName
	  Name of trigger being fired

	*/
	TriggerName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the fire trigger params
func (o *FireTriggerParams) WithTimeout(timeout time.Duration) *FireTriggerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the fire trigger params
func (o *FireTriggerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the fire trigger params
func (o *FireTriggerParams) WithContext(ctx context.Context) *FireTriggerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the fire trigger params
func (o *FireTriggerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithNamespace adds the namespace to the fire trigger params
func (o *FireTriggerParams) WithNamespace(namespace string) *FireTriggerParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the fire trigger params
func (o *FireTriggerParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithPayload adds the payload to the fire trigger params
func (o *FireTriggerParams) WithPayload(payload *swagger_models.KeyValue) *FireTriggerParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the fire trigger params
func (o *FireTriggerParams) SetPayload(payload *swagger_models.KeyValue) {
	o.Payload = payload
}

// WithTriggerName adds the triggerName to the fire trigger params
func (o *FireTriggerParams) WithTriggerName(triggerName string) *FireTriggerParams {
	o.SetTriggerName(triggerName)
	return o
}

// SetTriggerName adds the triggerName to the fire trigger params
func (o *FireTriggerParams) SetTriggerName(triggerName string) {
	o.TriggerName = triggerName
}

// WriteToRequest writes these params to a swagger request
func (o *FireTriggerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if o.Payload == nil {
		o.Payload = new(swagger_models.KeyValue)
	}

	if err := r.SetBodyParam(o.Payload); err != nil {
		return err
	}

	// path param triggerName
	if err := r.SetPathParam("triggerName", o.TriggerName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
