package swagger_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// ActionExec definition of the action, such as javascript code or the name of a container
// swagger:model ActionExec
type ActionExec struct {

	// The code to execute when kind is not 'blackbox'
	Code string `json:"code,omitempty"`

	// container image name when kind is 'blackbox'
	Image string `json:"image,omitempty"`

	// optional zipfile reference when code kind is 'nodejs'
	Init string `json:"init,omitempty"`

	// the type of action
	// Required: true
	Kind *string `json:"kind"`
}

// Validate validates this action exec
func (m *ActionExec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKind(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var actionExecTypeKindPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["nodejs","nodejs:6","nodejs:default","python","swift","swift:3","swift:default","java","blackbox"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		actionExecTypeKindPropEnum = append(actionExecTypeKindPropEnum, v)
	}
}

const (
	// ActionExecKindNodejs captures enum value "nodejs"
	ActionExecKindNodejs string = "nodejs"
	// ActionExecKindNodejs6 captures enum value "nodejs:6"
	ActionExecKindNodejs6 string = "nodejs:6"
	// ActionExecKindNodejsDefault captures enum value "nodejs:default"
	ActionExecKindNodejsDefault string = "nodejs:default"
	// ActionExecKindPython captures enum value "python"
	ActionExecKindPython string = "python"
	// ActionExecKindSwift captures enum value "swift"
	ActionExecKindSwift string = "swift"
	// ActionExecKindSwift3 captures enum value "swift:3"
	ActionExecKindSwift3 string = "swift:3"
	// ActionExecKindSwiftDefault captures enum value "swift:default"
	ActionExecKindSwiftDefault string = "swift:default"
	// ActionExecKindJava captures enum value "java"
	ActionExecKindJava string = "java"
	// ActionExecKindBlackbox captures enum value "blackbox"
	ActionExecKindBlackbox string = "blackbox"
)

// prop value enum
func (m *ActionExec) validateKindEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, actionExecTypeKindPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ActionExec) validateKind(formats strfmt.Registry) error {

	if err := validate.Required("kind", "body", m.Kind); err != nil {
		return err
	}

	// value enum
	if err := m.validateKindEnum("kind", "body", *m.Kind); err != nil {
		return err
	}

	return nil
}
