package swagger_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ActivationStderr activation stderr
// swagger:model ActivationStderr
type ActivationStderr struct {

	// Standard error of an activation
	Stderr string `json:"stderr,omitempty"`
}

// Validate validates this activation stderr
func (m *ActivationStderr) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
