package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteActionParams creates a new DeleteActionParams object
// with the default values initialized.
func NewDeleteActionParams() *DeleteActionParams {
	var ()
	return &DeleteActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteActionParamsWithTimeout creates a new DeleteActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteActionParamsWithTimeout(timeout time.Duration) *DeleteActionParams {
	var ()
	return &DeleteActionParams{

		timeout: timeout,
	}
}

// NewDeleteActionParamsWithContext creates a new DeleteActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteActionParamsWithContext(ctx context.Context) *DeleteActionParams {
	var ()
	return &DeleteActionParams{

		Context: ctx,
	}
}

/*DeleteActionParams contains all the parameters to send to the API endpoint
for the delete action operation typically these are written to a http.Request
*/
type DeleteActionParams struct {

	/*ActionName
	  Name of action

	*/
	ActionName string
	/*Namespace
	  The entity namespace

	*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete action params
func (o *DeleteActionParams) WithTimeout(timeout time.Duration) *DeleteActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete action params
func (o *DeleteActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete action params
func (o *DeleteActionParams) WithContext(ctx context.Context) *DeleteActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete action params
func (o *DeleteActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithActionName adds the actionName to the delete action params
func (o *DeleteActionParams) WithActionName(actionName string) *DeleteActionParams {
	o.SetActionName(actionName)
	return o
}

// SetActionName adds the actionName to the delete action params
func (o *DeleteActionParams) SetActionName(actionName string) {
	o.ActionName = actionName
}

// WithNamespace adds the namespace to the delete action params
func (o *DeleteActionParams) WithNamespace(namespace string) *DeleteActionParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the delete action params
func (o *DeleteActionParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param actionName
	if err := r.SetPathParam("actionName", o.ActionName); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
