package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/c3sr/openwhisk-go/models"
)

// NewUpdateActionParams creates a new UpdateActionParams object
// with the default values initialized.
func NewUpdateActionParams() *UpdateActionParams {
	var ()
	return &UpdateActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateActionParamsWithTimeout creates a new UpdateActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateActionParamsWithTimeout(timeout time.Duration) *UpdateActionParams {
	var ()
	return &UpdateActionParams{

		timeout: timeout,
	}
}

// NewUpdateActionParamsWithContext creates a new UpdateActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateActionParamsWithContext(ctx context.Context) *UpdateActionParams {
	var ()
	return &UpdateActionParams{

		Context: ctx,
	}
}

/*UpdateActionParams contains all the parameters to send to the API endpoint
for the update action operation typically these are written to a http.Request
*/
type UpdateActionParams struct {

	/*Action
	  The action being updated

	*/
	Action *models.ActionPut
	/*ActionName
	  Name of action

	*/
	ActionName string
	/*Namespace
	  The entity namespace

	*/
	Namespace string
	/*Overwrite
	  Overwrite item if it exists. Default is false.

	*/
	Overwrite *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update action params
func (o *UpdateActionParams) WithTimeout(timeout time.Duration) *UpdateActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update action params
func (o *UpdateActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update action params
func (o *UpdateActionParams) WithContext(ctx context.Context) *UpdateActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update action params
func (o *UpdateActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAction adds the action to the update action params
func (o *UpdateActionParams) WithAction(action *models.ActionPut) *UpdateActionParams {
	o.SetAction(action)
	return o
}

// SetAction adds the action to the update action params
func (o *UpdateActionParams) SetAction(action *models.ActionPut) {
	o.Action = action
}

// WithActionName adds the actionName to the update action params
func (o *UpdateActionParams) WithActionName(actionName string) *UpdateActionParams {
	o.SetActionName(actionName)
	return o
}

// SetActionName adds the actionName to the update action params
func (o *UpdateActionParams) SetActionName(actionName string) {
	o.ActionName = actionName
}

// WithNamespace adds the namespace to the update action params
func (o *UpdateActionParams) WithNamespace(namespace string) *UpdateActionParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the update action params
func (o *UpdateActionParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithOverwrite adds the overwrite to the update action params
func (o *UpdateActionParams) WithOverwrite(overwrite *string) *UpdateActionParams {
	o.SetOverwrite(overwrite)
	return o
}

// SetOverwrite adds the overwrite to the update action params
func (o *UpdateActionParams) SetOverwrite(overwrite *string) {
	o.Overwrite = overwrite
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Action == nil {
		o.Action = new(models.ActionPut)
	}

	if err := r.SetBodyParam(o.Action); err != nil {
		return err
	}

	// path param actionName
	if err := r.SetPathParam("actionName", o.ActionName); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if o.Overwrite != nil {

		// query param overwrite
		var qrOverwrite string
		if o.Overwrite != nil {
			qrOverwrite = *o.Overwrite
		}
		qOverwrite := qrOverwrite
		if qOverwrite != "" {
			if err := r.SetQueryParam("overwrite", qOverwrite); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
