package namespaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new namespaces API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for namespaces API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetAllEntitiesInNamespace gets all entities in a namespace

Get all entities in a namespace
*/
func (a *Client) GetAllEntitiesInNamespace(params *GetAllEntitiesInNamespaceParams) (*GetAllEntitiesInNamespaceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAllEntitiesInNamespaceParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getAllEntitiesInNamespace",
		Method:             "GET",
		PathPattern:        "/namespaces/{namespace}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAllEntitiesInNamespaceReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetAllEntitiesInNamespaceOK), nil

}

/*
GetAllNamespaces gets all namespaces for authenticated user

Get all namespaces for authenticated user
*/
func (a *Client) GetAllNamespaces(params *GetAllNamespacesParams) (*GetAllNamespacesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAllNamespacesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getAllNamespaces",
		Method:             "GET",
		PathPattern:        "/namespaces",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAllNamespacesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetAllNamespacesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
