package namespaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllNamespacesParams creates a new GetAllNamespacesParams object
// with the default values initialized.
func NewGetAllNamespacesParams() *GetAllNamespacesParams {

	return &GetAllNamespacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllNamespacesParamsWithTimeout creates a new GetAllNamespacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllNamespacesParamsWithTimeout(timeout time.Duration) *GetAllNamespacesParams {

	return &GetAllNamespacesParams{

		timeout: timeout,
	}
}

// NewGetAllNamespacesParamsWithContext creates a new GetAllNamespacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllNamespacesParamsWithContext(ctx context.Context) *GetAllNamespacesParams {

	return &GetAllNamespacesParams{

		Context: ctx,
	}
}

/*GetAllNamespacesParams contains all the parameters to send to the API endpoint
for the get all namespaces operation typically these are written to a http.Request
*/
type GetAllNamespacesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all namespaces params
func (o *GetAllNamespacesParams) WithTimeout(timeout time.Duration) *GetAllNamespacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all namespaces params
func (o *GetAllNamespacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all namespaces params
func (o *GetAllNamespacesParams) WithContext(ctx context.Context) *GetAllNamespacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all namespaces params
func (o *GetAllNamespacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllNamespacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
