package activations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNamespacesNamespaceActivationsActivationidLogsParams creates a new GetNamespacesNamespaceActivationsActivationidLogsParams object
// with the default values initialized.
func NewGetNamespacesNamespaceActivationsActivationidLogsParams() *GetNamespacesNamespaceActivationsActivationidLogsParams {
	var ()
	return &GetNamespacesNamespaceActivationsActivationidLogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNamespacesNamespaceActivationsActivationidLogsParamsWithTimeout creates a new GetNamespacesNamespaceActivationsActivationidLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNamespacesNamespaceActivationsActivationidLogsParamsWithTimeout(timeout time.Duration) *GetNamespacesNamespaceActivationsActivationidLogsParams {
	var ()
	return &GetNamespacesNamespaceActivationsActivationidLogsParams{

		timeout: timeout,
	}
}

// NewGetNamespacesNamespaceActivationsActivationidLogsParamsWithContext creates a new GetNamespacesNamespaceActivationsActivationidLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNamespacesNamespaceActivationsActivationidLogsParamsWithContext(ctx context.Context) *GetNamespacesNamespaceActivationsActivationidLogsParams {
	var ()
	return &GetNamespacesNamespaceActivationsActivationidLogsParams{

		Context: ctx,
	}
}

/*GetNamespacesNamespaceActivationsActivationidLogsParams contains all the parameters to send to the API endpoint
for the get namespaces namespace activations activationid logs operation typically these are written to a http.Request
*/
type GetNamespacesNamespaceActivationsActivationidLogsParams struct {

	/*Activationid
	  Name of activation to fetch

	*/
	Activationid string
	/*Namespace
	  The entity namespace

	*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get namespaces namespace activations activationid logs params
func (o *GetNamespacesNamespaceActivationsActivationidLogsParams) WithTimeout(timeout time.Duration) *GetNamespacesNamespaceActivationsActivationidLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get namespaces namespace activations activationid logs params
func (o *GetNamespacesNamespaceActivationsActivationidLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get namespaces namespace activations activationid logs params
func (o *GetNamespacesNamespaceActivationsActivationidLogsParams) WithContext(ctx context.Context) *GetNamespacesNamespaceActivationsActivationidLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get namespaces namespace activations activationid logs params
func (o *GetNamespacesNamespaceActivationsActivationidLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithActivationid adds the activationid to the get namespaces namespace activations activationid logs params
func (o *GetNamespacesNamespaceActivationsActivationidLogsParams) WithActivationid(activationid string) *GetNamespacesNamespaceActivationsActivationidLogsParams {
	o.SetActivationid(activationid)
	return o
}

// SetActivationid adds the activationid to the get namespaces namespace activations activationid logs params
func (o *GetNamespacesNamespaceActivationsActivationidLogsParams) SetActivationid(activationid string) {
	o.Activationid = activationid
}

// WithNamespace adds the namespace to the get namespaces namespace activations activationid logs params
func (o *GetNamespacesNamespaceActivationsActivationidLogsParams) WithNamespace(namespace string) *GetNamespacesNamespaceActivationsActivationidLogsParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get namespaces namespace activations activationid logs params
func (o *GetNamespacesNamespaceActivationsActivationidLogsParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *GetNamespacesNamespaceActivationsActivationidLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param activationid
	if err := r.SetPathParam("activationid", o.Activationid); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
