package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTriggerByNameParams creates a new GetTriggerByNameParams object
// with the default values initialized.
func NewGetTriggerByNameParams() *GetTriggerByNameParams {
	var ()
	return &GetTriggerByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTriggerByNameParamsWithTimeout creates a new GetTriggerByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTriggerByNameParamsWithTimeout(timeout time.Duration) *GetTriggerByNameParams {
	var ()
	return &GetTriggerByNameParams{

		timeout: timeout,
	}
}

// NewGetTriggerByNameParamsWithContext creates a new GetTriggerByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTriggerByNameParamsWithContext(ctx context.Context) *GetTriggerByNameParams {
	var ()
	return &GetTriggerByNameParams{

		Context: ctx,
	}
}

/*GetTriggerByNameParams contains all the parameters to send to the API endpoint
for the get trigger by name operation typically these are written to a http.Request
*/
type GetTriggerByNameParams struct {

	/*Namespace
	  The entity namespace

	*/
	Namespace string
	/*TriggerName
	  Name of trigger to fetch

	*/
	TriggerName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get trigger by name params
func (o *GetTriggerByNameParams) WithTimeout(timeout time.Duration) *GetTriggerByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get trigger by name params
func (o *GetTriggerByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get trigger by name params
func (o *GetTriggerByNameParams) WithContext(ctx context.Context) *GetTriggerByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get trigger by name params
func (o *GetTriggerByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithNamespace adds the namespace to the get trigger by name params
func (o *GetTriggerByNameParams) WithNamespace(namespace string) *GetTriggerByNameParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get trigger by name params
func (o *GetTriggerByNameParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithTriggerName adds the triggerName to the get trigger by name params
func (o *GetTriggerByNameParams) WithTriggerName(triggerName string) *GetTriggerByNameParams {
	o.SetTriggerName(triggerName)
	return o
}

// SetTriggerName adds the triggerName to the get trigger by name params
func (o *GetTriggerByNameParams) SetTriggerName(triggerName string) {
	o.TriggerName = triggerName
}

// WriteToRequest writes these params to a swagger request
func (o *GetTriggerByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param triggerName
	if err := r.SetPathParam("triggerName", o.TriggerName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
