package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ActivationLogs activation logs
// swagger:model ActivationLogs
type ActivationLogs struct {

	// Interleaved standard output and error of an activation
	Logs string `json:"logs,omitempty"`
}

// Validate validates this activation logs
func (m *ActivationLogs) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
