package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// KeyValue key value
// swagger:model KeyValue
type KeyValue struct {

	// key
	// Required: true
	Key *string `json:"key"`

	// Any JSON value
	// Required: true
	Value interface{} `json:"value"`
}

// Validate validates this key value
func (m *KeyValue) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKey(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KeyValue) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", m.Key); err != nil {
		return err
	}

	return nil
}

func (m *KeyValue) validateValue(formats strfmt.Registry) error {

	return nil
}
